services:
    # PostgreSQL
    database:
        image: postgres:15-alpine
        container_name: postgres
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app_network

    redis:
        image: redis:7-alpine
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - app_network

volumes:
    postgres_data:

networks:
    app_network:
        driver: bridge
